from fastapi.templating import Jinja2Templates
from itsdangerous import URLSafeSerializer
from app.config import settings
import logging

logger = logging.getLogger(__name__)

logger.info("Initializing Jinja2Templates central utility")

templates = Jinja2Templates(directory="templates")
serializer = URLSafeSerializer(settings.SECRET_KEY)

def get_csrf_token(request):
    """Retrieves the token generated by middleware from request scope."""
    token = request.scope.get("csrf_token", "")
    # logger.debug(f"CSRF token requested: {token}")
    return token

templates.env.globals["csrf_token"] = get_csrf_token
logger.info(f"Registered csrf_token in template globals: {templates.env.globals['csrf_token']}")
