"""Add swot to analysis

Revision ID: 109cbf876b21
Revises: 55866a8bf504
Create Date: 2026-01-29 04:59:54.866220

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '109cbf876b21'
down_revision = '55866a8bf504'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('swot', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'swot')
    # ### end Alembic commands ###
