"""add_retry_count_to_jobs

Revision ID: 1d1a2706b6cd
Revises: b75ac426a4b9
Create Date: 2026-01-26 02:43:11.003704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d1a2706b6cd'
down_revision = 'b75ac426a4b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('scraping_jobs', sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scraping_jobs', 'retry_count')
    # ### end Alembic commands ###
