"""Add analysis columns

Revision ID: 55866a8bf504
Revises: 68845fd5cf5e
Create Date: 2026-01-29 04:11:39.188843

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '55866a8bf504'
down_revision = '68845fd5cf5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_results', sa.Column('profitability_score', sa.Numeric(precision=5, scale=2), server_default='0', nullable=False))
    op.add_column('analysis_results', sa.Column('score_breakdown', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('analysis_results', sa.Column('trend_analysis', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('analysis_results', sa.Column('competition_data', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('analysis_results', sa.Column('feature_gaps', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('analysis_results', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('analysis_results', 'version')
    op.drop_column('analysis_results', 'feature_gaps')
    op.drop_column('analysis_results', 'competition_data')
    op.drop_column('analysis_results', 'trend_analysis')
    op.drop_column('analysis_results', 'score_breakdown')
    op.drop_column('analysis_results', 'profitability_score')
    # ### end Alembic commands ###
