"""fresh_start

Revision ID: 91baf9f43d1a
Revises: None
Create Date: 2026-01-26 01:53:49.826486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91baf9f43d1a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
